services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - magic_link_db_volume:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    networks:
      - magic_link_internal

  redis:
    image: redis:7-alpine
    volumes:
      - magic_link_redis_volume:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - magic_link_internal

  app:
    build:
      context: ./backend
      target: dev
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: ${PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      HMAC_SECRET: ${HMAC_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS}
    ports:
      - "${PORT}:${PORT}"
      - "9090:9090"
    networks:
      - magic_link_internal

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - magic_link_internal

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@magic-link-demo.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - magic_link_internal

volumes:
  magic_link_db_volume:
  magic_link_redis_volume:
  prometheus_data:

networks:
  magic_link_internal:
    driver: bridge
