export const creditOptions = [
  {
    name: "Starter Plan",
    amount: "10,000",
    price: "$31",
    bonus: null,
    total: null,
    package_code: "starter",
  },
  {
    name: "Basic Plan",
    amount: "25,000",
    price: "$42",
    bonus: null,
    total: null,
    package_code: "basic",
  },
  {
    name: "Standard Plan",
    amount: "50,000",
    price: "$65",
    bonus: null,
    total: null,
    package_code: "standard",
  },
  {
    name: "Pro Plan",
    amount: "100,000",
    price: "$110",
    bonus: null,
    total: null,
    package_code: "pro",
  },
  {
    name: "Business Plan",
    amount: "500,000",
    price: "$220",
    bonus: null,
    total: null,
    package_code: "business",
  },
  {
    name: "Enterprise Plan",
    amount: "1,000,000",
    price: "$331",
    bonus: null,
    total: null,
    package_code: "enterprise",
  },
  {
    name: "Elite Plan",
    amount: "2,000,000",
    price: "$577",
    bonus: null,
    total: null,
    package_code: "elite",
  },
  {
    name: "Premium 3M Plan",
    amount: "3,000,000",
    price: "$824",
    bonus: "1M",
    total: "4 Million Credits",
    package_code: "premium_3m",
  },
  {
    name: "Premium 4M Plan",
    amount: "4,000,000",
    price: "$1,036",
    bonus: "1M",
    total: "5 Million Credits",
    package_code: "premium_4m",
  },
  {
    name: "Premium 5M Plan",
    amount: "5,000,000",
    price: "$1,223",
    bonus: "1M",
    total: "6 Million Credits",
    package_code: "premium_5m",
  },
  {
    name: "Ultimate Plan",
    amount: "10,000,000",
    price: "$2,150",
    bonus: "2M",
    total: "12 Million Credits",  
    package_code: "ultimate",
  },
];
